name: Build Debian package

on:
  workflow_dispatch:
  push:

env:
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packaging dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            python3 python3-dev python3-pip python3-venv python3-all \
            dh-python debhelper devscripts dput software-properties-common \
            python3-distutils python3-setuptools python3-wheel python3-stdeb

      - name: Build Debian/Apt sdist_dsc
        run: |
          rm -Rf deb_dist/*
          python3 setup.py --command-packages=stdeb.command sdist_dsc

      - name: Build Debian/Apt bdist_deb
        run: |
          python3 setup.py --command-packages=stdeb.command bdist_deb

      - uses: actions/upload-artifact@v2
        with:
          name: artifact-deb
          path: |
            bdist_deb/*.deb
